[package]
name = "fort-rs-bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
clap = { version = "3", features = ["derive"]}
fort-rs-core = { path = "../core" }
serde = { version = "1", features = ["derive"]}
serde_json = "1"
